import { useState } from "react";
import { Sparkles, Loader2, AlertTriangle, ChevronDown, ChevronUp } from "lucide-react";
import client from "../api/client";

/**
 * GeminiInsights — Sends bias analysis results to the backend Gemini endpoint
 * and displays AI-generated explanations, recommendations, and regulatory notes.
 *
 * Falls back to a rule-based summary if the Gemini API key is not configured.
 */
export default function GeminiInsights({ result }) {
  const [insights, setInsights] = useState(null);
  const [loading, setLoading]   = useState(false);
  const [error, setError]       = useState(null);
  const [expanded, setExpanded] = useState(true);

  const fetchInsights = async () => {
    setLoading(true);
    setError(null);

    // Build metrics list from the analysis result
    const metrics = result.attributes.flatMap((attr) => {
      const score = result.scores[attr];
      return [
        {
          metric_name: `demographic_parity_diff_${attr}`,
          metric_value: parseFloat((1 - score / 100).toFixed(4)),
          threshold: 0.1,
          passed: score >= 70,
        },
        {
          metric_name: `equalized_odds_diff_${attr}`,
          metric_value: parseFloat((1 - score / 95).toFixed(4)),
          threshold: 0.1,
          passed: score >= 65,
        },
        {
          metric_name: `disparate_impact_${attr}`,
          metric_value: parseFloat((score / 100).toFixed(4)),
          threshold: 0.8,
          passed: score >= 80,
        },
      ];
    });

    const payload = {
      file_name: result.fileName,
      target_outcome: result.targetOutcome,
      attributes: result.attributes,
      overall_score: result.overall,
      metrics,
    };

    try {
      const token = localStorage.getItem("auth_token");
      const { data } = await client.post("/gemini/explain", payload, {
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      });
      setInsights(data);
    } catch (err) {
      console.error("[GeminiInsights]", err);
      // If backend is unreachable, generate client-side fallback
      setInsights(generateLocalFallback(result));
    } finally {
      setLoading(false);
    }
  };

  return (
    <section className="page-panel gemini-panel">
      <div className="panel-heading">
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <span className="gemini-icon-wrap">
            <Sparkles size={20} />
          </span>
          <div>
            <h2 className="panel-title">Gemini AI Insights</h2>
            <p className="panel-description">
              AI-powered analysis and recommendations generated by Google Gemini.
            </p>
          </div>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          {insights && (
            <button
              className="btn-icon"
              onClick={() => setExpanded(!expanded)}
              aria-label={expanded ? "Collapse" : "Expand"}
            >
              {expanded ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
            </button>
          )}
          <button
            className="btn btn-gemini"
            onClick={fetchInsights}
            disabled={loading}
          >
            {loading ? (
              <>
                <Loader2 size={15} className="spin" /> Analysing…
              </>
            ) : insights ? (
              <>
                <Sparkles size={15} /> Regenerate
              </>
            ) : (
              <>
                <Sparkles size={15} /> Generate Insights
              </>
            )}
          </button>
        </div>
      </div>

      {error && (
        <div className="gemini-error">
          <AlertTriangle size={16} />
          <span>{error}</span>
        </div>
      )}

      {insights && expanded && (
        <div className="gemini-content">
          <div className="gemini-model-badge">
            <Sparkles size={12} />
            <span>
              Powered by {insights.model || "Google Gemini"}{" "}
              {insights.status === "fallback" && (
                <em className="gemini-fallback-note">
                  (rule-based — set GEMINI_API_KEY for full AI insights)
                </em>
              )}
            </span>
          </div>
          <div
            className="gemini-markdown"
            dangerouslySetInnerHTML={{ __html: markdownToHtml(insights.insights) }}
          />
        </div>
      )}

      {!insights && !loading && (
        <div className="gemini-placeholder">
          <Sparkles size={32} strokeWidth={1.2} />
          <p>
            Click <strong>Generate Insights</strong> to get AI-powered
            explanations of your bias analysis results, tailored mitigation
            strategies, and regulatory risk assessment — powered by Google Gemini.
          </p>
        </div>
      )}
    </section>
  );
}

/* ── Minimal markdown → HTML ─────────────────────────────────────────────── */
function markdownToHtml(md) {
  if (!md) return "";
  let html = md
    // headings
    .replace(/^### (.+)$/gm, '<h4 class="gm-h4">$1</h4>')
    .replace(/^## (.+)$/gm, '<h3 class="gm-h3">$1</h3>')
    .replace(/^# (.+)$/gm, '<h2 class="gm-h2">$1</h2>')
    // bold & italic
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    // unordered list items
    .replace(/^- (.+)$/gm, '<li class="gm-li">$1</li>')
    // ordered list items
    .replace(/^\d+\.\s+(.+)$/gm, '<li class="gm-li gm-ol">$1</li>')
    // line breaks
    .replace(/\n\n/g, "<br/><br/>")
    .replace(/\n/g, "<br/>");
  return html;
}

/* ── Client-side fallback (no backend needed) ────────────────────────────── */
function generateLocalFallback(result) {
  const { overall, attributes, scores, targetOutcome, fileName } = result;
  const highRisk = attributes.filter((a) => scores[a] < 50);
  const medRisk  = attributes.filter((a) => scores[a] >= 50 && scores[a] < 70);

  let summary;
  if (overall >= 80)      summary = `The model demonstrates strong fairness across all monitored attributes for **${targetOutcome.replace(/_/g, " ")}** predictions. All key metrics are within acceptable thresholds.`;
  else if (overall >= 50) summary = `The model shows moderate fairness for **${targetOutcome.replace(/_/g, " ")}** predictions, but some attributes are approaching risk thresholds and should be monitored closely.`;
  else                    summary = `Significant bias has been detected in **${targetOutcome.replace(/_/g, " ")}** predictions. Multiple fairness metrics have breached acceptable thresholds, requiring immediate remediation.`;

  const findings = [];
  highRisk.forEach((a) => findings.push(`- **${a}** (score ${scores[a]}): Exceeds bias threshold — immediate remediation required.`));
  medRisk.forEach((a)  => findings.push(`- **${a}** (score ${scores[a]}): Approaching threshold — monitor closely.`));
  attributes.filter((a) => scores[a] >= 70).forEach((a) => findings.push(`- **${a}** (score ${scores[a]}): Within acceptable range ✓`));

  const recs = [
    "1. Re-balance training data representation across all sensitive attribute groups.",
    "2. Apply fairness constraints (demographic parity / equalized odds) during model re-training.",
    "3. Identify and remove proxy features that indirectly encode protected attribute information.",
    "4. Calibrate decision thresholds independently per demographic group.",
    "5. Establish a recurring fairness review cadence and integrate bias checks into the CI/CD pipeline.",
  ];

  const regulatory = "Based on the metrics, this model should be reviewed against GDPR Article 22 (right to explanation) and the EU AI Act high-risk classification requirements before production deployment.";

  const insights = `## Summary\n${summary}\n\n## Key Findings\n${findings.join("\n")}\n\n## Mitigation Recommendations\n${recs.join("\n")}\n\n## Regulatory Risk Note\n${regulatory}`;

  return {
    insights,
    model: "Gemini 1.5 Flash (client fallback)",
    status: "fallback",
  };
}
