"""
Gemini AI Router
─────────────────
Exposes an endpoint that accepts bias analysis results and returns
AI-generated explanations and recommendations powered by Google Gemini.
"""

from fastapi import APIRouter, Depends
from pydantic import BaseModel
from typing import List, Optional
from app.utils.auth import get_current_user
from app.services.gemini_service import generate_bias_insights

router = APIRouter()


class MetricItem(BaseModel):
    metric_name: str
    metric_value: float
    threshold: float
    passed: bool


class GeminiExplainRequest(BaseModel):
    file_name: str
    target_outcome: str
    attributes: List[str]
    overall_score: int
    metrics: List[MetricItem]


@router.post("/explain")
async def explain_bias(body: GeminiExplainRequest, current_user=Depends(get_current_user)):
    """
    Accept bias analysis results and return AI-powered insights
    generated by Google Gemini.
    """
    bias_data = {
        "file_name": body.file_name,
        "target_outcome": body.target_outcome,
        "attributes": body.attributes,
        "overall_score": body.overall_score,
        "metrics": [m.model_dump() for m in body.metrics],
    }
    result = await generate_bias_insights(bias_data)
    return result
